-- MySQL Script generated by MySQL Workbench
-- Fri Feb  3 09:34:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DER_ProjetoIntegrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DER_ProjetoIntegrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DER_ProjetoIntegrador` DEFAULT CHARACTER SET utf8 ;
USE `DER_ProjetoIntegrador` ;

-- -----------------------------------------------------
-- Table `DER_ProjetoIntegrador`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER_ProjetoIntegrador`.`tb_usuarios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `usuarioEmail` VARCHAR(255) NOT NULL,
  `cpf` BIGINT NOT NULL,
  `endereco` VARCHAR(500) NOT NULL,
  `numero` BIGINT NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER_ProjetoIntegrador`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER_ProjetoIntegrador`.`tb_categorias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(500) NOT NULL,
  `regiao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER_ProjetoIntegrador`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER_ProjetoIntegrador`.`tb_produtos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(500) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `preco` DECIMAL(6,2) NOT NULL,
  `embalagem` VARCHAR(255) NOT NULL,
  `dicasPlantacao` VARCHAR(1000) NOT NULL,
  `categorias_id` BIGINT NOT NULL,
  `usuarios_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_produtos_tb_categorias_idx` (`categorias_id` ASC) VISIBLE,
  INDEX `fk_tb_produtos_tb_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produtos_tb_categorias`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `DER_ProjetoIntegrador`.`tb_categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produtos_tb_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `DER_ProjetoIntegrador`.`tb_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
